### ISSUE TITLE
Owo what's this

### ISSUE THREAD

**Issue by Kaffeedor** [The-Order-of-the-Simulation/Path-Tracing-Renderer#2]
Just been wondering what exactly this is my friend. Can you tell me?

**Comment by Zi7ar21** [comment]
😂 It's a path-tracing renderer

**Comment by Zi7ar21** [comment]
You can find a pre-built binary for the Vulkan version at [https://github.com/The-Order-of-the-Simulation/Path-Tracing-Renderer/releases](https://github.com/The-Order-of-the-Simulation/Path-Tracing-Renderer/releases)

I'm currently working on a CPU-based version that you can find in the CPU branch at [https://github.com/The-Order-of-the-Simulation/Path-Tracing-Renderer/tree/cpu](https://github.com/The-Order-of-the-Simulation/Path-Tracing-Renderer/tree/cpu)

**Comment by Zi7ar21** [comment]
The CPU and GPU branches are now merged, the link to the CPU-based branch will no longer work.

**Comment by Zi7ar21** [comment]
Alright I'm gonna close this now lmao
